#!/bin/bash
# Xiao-Themes Installer Script
# This script was based by 13atm01 and JohnKun136NVCP
# Grub2 Theme installer 
# Do not edit this file !!

ROOT_ID=$(id -u)
THEME_DIR="/usr/share/grub/themes"
THEME_NAME="$1"
THEME_PATH="$THEME_DIR/$THEME_NAME"
DELAY_TIME=10 #Time to enter root password

# Colours

bblue="\033[38;5;45m"
yellowp="\033[38;5;214m"
INFO_COLOR=" \033[0;36m"                                  # info color
SUCCESS_COLOR=" \033[0;32m"                               # success color
ERROR_COLOR=" \033[0;31m"                                 # error color
WARN_COLOR=" \033[0;33m"                                  # warning color
B_DFC=" \033[1;37m"                                       # bold default color
B_INFO=" \033[1;36m"                                      # bold info color
B_SUC=" \033[1;32m"                                       # bold success color
B_ERROR=" \033[1;31m"                                     # bold error color
B_WARNING=" \033[1;33m"  


# Title theme ASCII art
title(){
    echo -e "$bblue\t                   _   __    ______ _                        \e[0m"
    echo -e "$bblue\t  () |            | | /  )  (_) |  | |                       \e[0m"
    echo -e "$bblue\t  /\/| ,_         | |   /       |  | |     _   _  _  _    _  \e[0m"
    echo -e "$bblue\t /   |/  |  |   | |/ \_/      _ |  |/ \   |/  / |/ |/ |  |/  \e[0m"
    echo -e "$bblue\t/(__/    |_/ \_/|_/\_//___   (_/   |   |_/|__/  |  |  |_/|__/\e[0m"
    echo -e "$yellowp\t\t\t⢰⣶⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀\e[0m"
    echo -e "$yellowp\t\t\t⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣾⣿⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠘⢿⣿⣿⣿⣿⣦⣀⣀⣀⣄⣀⣀⣠⣀⣤⣶⣿⣿⣿⣿⣿⠇⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠈⠻⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⠋⠀⠀⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀⢠⣿⣿\033[38;5;94m⡏\e[00m⠆\033[38;5;214m⢹⣿⣿⣿⣿⣿⣿\e[00m⠒\033[38;5;214m⠈⣿⣿⣿⣇⠀⠀⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀⣼⣿⣿⣷⣶⣿⣿⣛⣻⣿⣿⣿⣶⣾⣿⣿⣿⣿⡀⠀⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀\033[38;5;95m⡁⠀⠈\033[38;5;214m⣿⣿⣿⣿⢟⣛⡻⣿⣿⣿⣟\033[38;5;95m⠀⠀⠈\033[38;5;214m⣿⡇⠀⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀⢿⣶⣿⣿⣿⣿⣿\033[38;5;209m⡻⣿⡿\033[38;5;214m⣿⣿⣿⣿⣶⣶⣾⣿⣿⠀⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀\e[0m"
    echo -e "$yellowp\t\t\t⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀\e[0m"
}

menu(){
    case ${1} in
    "-s"|"--success")
        echo -e "${B_SUC} ${2} ${B_DFC}";;              # Success message
    "-e"|"--error")
        echo -e "${B_ERROR} ${2} ${B_DFC}";;            # Error message
    "-w"|"--warning")
        echo -e "${B_WARNING} ${2} ${B_DFC}";;          # Warning message
    "-i"|"--info")
        echo -e "${B_INFO} ${2} ${B_DFC}";;             # Info message
    *)
    echo -e "$@";; # Default message
    esac
    
}

# Null commands
function command(){
    command -v $1 >/dev/null
}



# Menu 
title
# Running countdown
for ((i=10; i>0; i--)); do
    echo -ne "\r${B_INFO}Press enter to begin installation${B_DFC}(automatically install after ${i}s)${B_WARNING}:${B_DFC}"
    read -s -n 1 -t 1 key
    if [ $? -eq 0 ]; then
        break
    fi
done
# Check if the user is root
menu -w "\n Checking if you are root... \n"
if [ "$ROOT_ID" -eq 0 ]; then
    # Create themes directory if it doesn't exist
    menu -i "\n Checking if themes directory exists... \n"
    [[ -d ${THEME_PATH} ]] && rm -rf ${THEME_PATH}
    mkdir -p ${THEME_PATH}
    # Copy theme
    menu -i "\n Installing ${THEME_NAME} theme... \n"
    cp -a ${THEME_NAME}/* ${THEME_PATH}

    # Set theme
    menu -i "\n Setting ${Theme_NAME} as default theme... \n"

    # Backup grub configuration
    cp -an /etc/default/grub /etc/default/grub.bak

    grep -an "GRUB_THEME" /etc/default/grub 2>&1 >/dev/null && sed -i '/GRUB_THEME/d' /etc/default/grub
    echo "GRUB_THEME=\"${THEME_PATH}/theme.txt\"" >> /etc/default/grub
    menu -i "\n Finalizing installation... \n"
    # Update grub
    menu -i "\n Updating grub... \n"
    if command update-grub; then
        update-grub
    elif command grub-mkconfig; then
        grub-mkconfig -o /boot/grub/grub.cfg
    elif command grub2-mkconfig; then
        if command zypper;then
            grub2-mkconfig -o /boot/grub2/grub.cfg
        elif command dnf;then
            grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
        fi
    fi
    # Success message
    menu -s "\n ${THEME_NAME} theme installed successfully! \n"
    else
    # Check if the user is root
    menu -e "\n You are not root, please run this script as root \n"
fi
